### ISSUE TITLE
Add role exception on MariaDB

### ISSUE THREAD

**Issue by ineilson** [GOCDB/gocdb#255] opened 2020-09-10 11:33 UTC
Requesting a new role fails -

`An exception occurred while executing 'INSERT INTO RoleActionRecords (actionDate, updatedByUserId, updatedByUserPrinciple, roleId, rolePreStatus, roleNewStatus, roleTypeId, roleTypeName, roleTargetOwnedEntityId, roleTargetOwnedEntityType, roleUserId, roleUserPrinciple) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["2020-09-10 11:18:13", 2, "Ian Neilson", null, "STATUS_PENDING", "STATUS_PENDING", 2, "Site Security Officer", 3, "site", 2, "Ian Neilson"]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'roleId' cannot be null`

https://github.com/GOCDB/gocdb/blob/1fe9d2b8e45320757423143c1dd45b69fba1e587/lib/Gocdb_Services/Role.php#L525

```
            // getRoleTypeName throws a NoResultException if the roleType with the
            // specfied name don't exist in in the DB.
            $roleType = $this->getRoleTypeByName($roleTypeName);
            $r = new \Role($roleType, $user, $entity, $roleStatus);
            $this->em->persist($r);

            // create a RoleActionRecord after role has been persisted (to get id)
            $rar = \RoleActionRecord::construct($user, $r, \RoleStatus::PENDING);
            $this->em->persist($rar);

            $this->em->flush();
```

This is 'fixed' by adding an additional flush() after the Role persist() but before the RoleActionRecord construction, contrary to what the RoleActionRecord comment implies should happen. 

The failure comes when using MariaDB - does it 'work' on Oracle/production? Is this a/my Doctrine configuration issue?

**Comment by gregcorbett** [comment] 2020-09-10 15:40
Can replicate the issue on MariaDB

**Comment by gregcorbett** [comment] 2020-09-10 15:54
Looks like its coming from here: https://github.com/GOCDB/gocdb/blob/dev/lib/Doctrine/entities/RoleActionRecord.php#L186

`$role->getStatus()` appears to be set, but not `$role->getId()`

**Comment by gregcorbett** [comment] 2020-09-10 16:14
After https://github.com/GOCDB/gocdb/blob/dev/lib/Gocdb_Services/Role.php#L522, with a ORACLE DB `$r->getId()` is set, but on MariaDB it remains unset - hence the error later on....

**Comment by ineilson** [comment] 2020-09-10 16:43
Exactly. But id is auto-generated by the db - the question is at what time - on persist or flush?

    /** @Id @Column(type="integer") @GeneratedValue  */

**Comment by gregcorbett** [comment] 2020-09-29 07:32
I'm going to close this issue as it's a duplicate of #125.

**Closed** 2020-09-29 07:54 UTC
Labels: bug, duplicate, help wanted
